sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    region: cn-beijing
    bucketName: web-amadeus
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wxd1305d902df8301a
    secret: 945c5c63d36cc7d8d89cc21621622ace
